# Generated by Django 4.1.7 on 2023-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(1, 'Know'), (2, 'Dont know'), (3, 'Repeat'), (4, 'New')], default=4),
        ),
    ]
